### ISSUE TITLE
Cron job errors

### ISSUE THREAD

**Issue by ckabuya** [twostack/docker-bitcoin-node#1]
On Windows, I was getting this error 
 => [ 8/11] COPY bashrc /root/.bashrc                                                                                    0.8s
 => ERROR [ 9/11] RUN crontab /tmp/scheduler.txt                                                                         2.5s
------
 > [ 9/11] RUN crontab /tmp/scheduler.txt:
#14 2.043 "/tmp/scheduler.txt":1: bad minute
#14 2.043 errors in crontab file, can't install.
------
executor failed running [/bin/sh -c crontab /tmp/scheduler.txt]: exit code: 1

I edited the schedule.txt file as explained here https://superuser.com/questions/347459/bad-minute-in-crontab.
The problem got sorted.

**Comment by stephanfeb** [comment]
Hi @ckabuya , thanks for the bug report!

Could you generate a pull request with your fix ?

Cheers
Stephan
